# Generated by Django 5.1.2 on 2024-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blogpost_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
