# Generated by Django 5.1.2 on 2024-11-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_blogpost_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LikedBlogs',
        ),
    ]
