# Generated by Django 5.1.2 on 2024-11-06 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_At',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 11, 58, 41, 197779, tzinfo=datetime.timezone.utc)),
        ),
    ]
