# Generated by Django 5.1.2 on 2024-11-07 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_media_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_At',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 11, 59, 14, 472854, tzinfo=datetime.timezone.utc)),
        ),
    ]
