# Generated by Django 5.1.2 on 2024-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_otp_expires_at_likedblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(default='no summary', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super Admin', 'Super Admin'), ('User', 'User')], default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
