# Generated by Django 5.1.2 on 2024-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_blogpost_summary_user_designation_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.TextField(default='media/scotland_UqE7rEB.jpg'),
        ),
    ]
